CREATE OR REPLACE TRIGGER JOMUMA1.TRG_USERHISTORY
  AFTER DELETE OR UPDATE ON JOMUMA1.AJEDRECI
  REFERENCING NEW ROW AS N OLD ROW AS O
  FOR EACH ROW MODE DB2ROW
BEGIN

  IF DELETING THEN
    INSERT INTO JOMUMA1.USER_HISTORY VALUES (
      CURRENT_TIMESTAMP,
      CURRENT_USER,
      'D',
      O.NOMBRE,
      '',
      O.APELLIDOS,
      '',
      O.ELO,
      0
    );
  END IF;

  IF UPDATING THEN
    INSERT INTO JOMUMA1.USER_HISTORY VALUES (
      CURRENT_TIMESTAMP,
      CURRENT_USER,
      'U',
      O.NOMBRE,
      N.NOMBRE,
      O.APELLIDOS,
      N.APELLIDOS,
      O.ELO,
      N.ELO
    );
  END IF;
END;
