-- TIPOS DE CURSORES

-- Si no especificamos nada, el sistema lo trata como un cursor asensitive.
-- A veces veremos los cambios y a veces no.
DECLARE C1 CURSOR FOR
    SELECT * FROM CUSTOMERS;

DECLARE C1 ASENSITIVE CURSOR FOR
    SELECT * FROM CUSTOMERS;

-- Para un comportamiento específico, es mejor definir explícitamente el tipo de cursor.
-- Se puede definir como INSENSITIVE o SENSITIVE, tanto en cursores normales como en scroll cursors.
DECLARE C2 INSENSITIVE SCROLL CURSOR FOR
    SELECT * FROM CUSTOMERS;

DECLARE C3 SENSITIVE SCROLL CURSOR FOR
    SELECT * FROM CUSTOMERS;


-- EJEMPLO CREACION DE TABLAS Y DATA
CREATE TABLE CUSTOMERS {
  CUSTOMER_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CUSTOMER_NAME VARCHAR(100),
  CUSTOMER_EMAIL VARCHAR(100)
};

CREATE TABLE ORDERS {
  ORDER_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CUSTOMER_ID INT,
  ORDER_DATE DATE,
  ORDER_AMOUNT DECIMAL(10, 2),
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
};

INSERT INTO CUSTOMERS (CUSTOMER_NAME, CUSTOMER_EMAIL) VALUES
('John Doe', 'john@example.com'),
('Jane Smith', 'jane@example.com'),
('Alice Johnson', 'alice@example.com');

INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, ORDER_AMOUNT) VALUES
(1, CURRENT_DATE, 100.00),
(2, CURRENT_DATE, 150.00),
(3, CURRENT_DATE, 200.00);