-- Campo TEXT con longitud fija de 10000
CREATE OR REPLACE TABLE JOMUMA1.LOG_CHAR (
  RESULT CHAR(1),
  TEXT CHAR(10000)
);

INSERT INTO JOMUMA1.LOG_CHAR VALUES('0', 'CORRECTO');
INSERT INTO JOMUMA1.LOG_CHAR VALUES('1', 'REGISTRO DUPLICADO. POR FAVOR MIRE EL PROGRAMA CMP0001');

-- Campo TEXT con longitud variable de hasta 10000
CREATE OR REPLACE TABLE JOMUMA1.LOG_VARCHAR FOR SYSTEM NAME LOGVARCHAR (
  RESULT CHAR(1),
  TEXT VARCHAR(10000)
);

INSERT INTO JOMUMA1.LOG_VARCHAR VALUES('0', 'CORRECTO');
INSERT INTO JOMUMA1.LOG_VARCHAR VALUES('1', 'REGISTRO DUPLICADO. POR FAVOR MIRE EL PROGRAMA CMP0001');
